// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCpHxVyqD-L15LCv6qcx2yMpOc9Dqfu54U',
//     appId: '1:604856355250:web:e853b1b7affcf43321fcab',
//     messagingSenderId: '604856355250',
//     projectId: 'test-609e7',
//     authDomain: 'test-609e7.firebaseapp.com',
//     storageBucket: 'test-609e7.firebasestorage.app',
//     measurementId: 'G-JTQ9RVQWD0',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCDCVZjA8bmCekp6LhoSolaNjMFgwfq6aM',
//     appId: '1:604856355250:android:c46ca2053dbf3ead21fcab',
//     messagingSenderId: '604856355250',
//     projectId: 'test-609e7',
//     storageBucket: 'test-609e7.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAjmN_a3Qek73dcHYJQY7RqtOiO848T_CY',
//     appId: '1:604856355250:ios:32fe355f56c22b1a21fcab',
//     messagingSenderId: '604856355250',
//     projectId: 'test-609e7',
//     storageBucket: 'test-609e7.firebasestorage.app',
//     iosBundleId: 'com.example.testadm',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAjmN_a3Qek73dcHYJQY7RqtOiO848T_CY',
//     appId: '1:604856355250:ios:32fe355f56c22b1a21fcab',
//     messagingSenderId: '604856355250',
//     projectId: 'test-609e7',
//     storageBucket: 'test-609e7.firebasestorage.app',
//     iosBundleId: 'com.example.testadm',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCpHxVyqD-L15LCv6qcx2yMpOc9Dqfu54U',
//     appId: '1:604856355250:web:50dac89135485e8121fcab',
//     messagingSenderId: '604856355250',
//     projectId: 'test-609e7',
//     authDomain: 'test-609e7.firebaseapp.com',
//     storageBucket: 'test-609e7.firebasestorage.app',
//     measurementId: 'G-VC5SD9EDXE',
//   );
// }
